name: Qodana Quality

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  qodana-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v5.0.2
        with:
          args: "--fail-threshold,100"
          upload-result: true

      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

      - name: Generate docs
        run: |
          pip install pdoc
          pdoc -d google -o ${{ runner.temp }}/qodana/results/report/docs unipa

      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ runner.temp }}/qodana/results/report/docs
          name: docs

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./
