name: Sync Back to Develop
# see https://bharathvaj.me/blog/keep-two-branches-in-sync

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync:
    name: Syncing branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Opening pull request
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: 'master'
          TO_BRANCH: 'develop'
